version: '3'

services:
  postgres:
    image: 'postgres:9.5'
    volumes:
      - 'postgres:/var/lib/postgresql/data'
    environment:
      POSTGRES_PASSWORD: root

  app:
    build: .
    command: bash start.sh
    ports:
      - '3001:3001'
    volumes:
      - '.:/product_sales_api'
      - gems:/gems
    depends_on:
      - postgres
 
volumes:
  postgres:
  gems:
  web:
