default: &default
  sites: ['olx']

  olx:
    uri: 'https://ro.olx.com.br/?q='
    cards: '#ad-list li'
    name: 'h2.fnmrjs-10.deEIZJ'
    price: 'p.fnmrjs-16.jqSHIm'

development:
  <<: *default

test:
  <<: *default

production:
  <<: *default
