default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  username: <%= ENV.fetch("db_user") { 'postgres' } %>
  password: <%= ENV.fetch("db_pass") { 'root' } %>
  host: <%= ENV.fetch("db_pass") { postgres } %>
  port: <%= ENV.fetch("db_pass") %>

development:
  <<: *default
  database: product_sales_api_development

test:
  <<: *default
  database: product_sales_api_test

production:
  <<: *default
  database: product_sales_api_production
